---
- name: "install plugin dependencies with apt"
  apt:
    name: "{{ asdf_apt_optional_dependencies }}"
    update_cache: yes
    install_recommends: no
  retries: "{{ remote_package_retries }}"
  register: apt_result
  until: apt_result is succeeded
  become: True
  when: ansible_os_family == "Debian"

- name: "install plugin dependencies with yum"
  yum:
    name: "{{ asdf_yum_optional_dependencies }}"
    update_cache: yes
  retries: "{{ remote_package_retries }}"
  register: yum_result
  until: yum_result is succeeded
  become: True
  when: ansible_os_family == "RedHat"

- name: "install plugins"
  shell:
    source {{ asdf_script }} && asdf plugin-add {{ item.name }} {{ item.repository | default() }}
  args:
    executable: bash
    creates: "{{ asdf_dir }}/plugins/{{ item.name }}"
  with_items: "{{ asdf_plugins }}"
  when: asdf_plugins | length > 0
  become: True
  become_user: "{{ asdf_user }}"
  ignore_errors: True

- name: "nodejs specific tasks"
  include_tasks: "plugins/nodejs.yml"
  when: '"nodejs" in item["name"]'
  with_items: "{{ asdf_plugins }}"

- name: "erlang specific tasks"
  include_tasks: "plugins/erlang.yml"
  when: '"erlang" in item["name"]'
  with_items: "{{ asdf_plugins }}"

- name: "python specific tasks"
  include_tasks: "plugins/python.yml"
  when: '"python" in item["name"]'
  with_items: "{{ asdf_plugins }}"

- name: "ruby specific tasks"
  include_tasks: "plugins/ruby.yml"
  when: '"ruby" in item["name"]'
  with_items: "{{ asdf_plugins }}"

- name: "php specific tasks"
  include_tasks: "plugins/php.yml"
  when: '"php" in item["name"]'
  with_items: "{{ asdf_plugins }}"

- name: "install apps"
  shell:
    source {{ asdf_script }} && asdf install {{ item.0.name }} {{ item.1 }}
  args:
    executable: bash
    creates: "{{ asdf_dir }}/installs/{{ item.0.name }}/{{ item.1 }}"
  with_subelements:
    - "{{ asdf_plugins }}"
    - versions
    - flags:
      skip_missing: True
  when: asdf_plugins | length > 0
  become: True
  become_user: "{{ asdf_user }}"

- name: "uninstall apps"
  shell:
    source {{ asdf_script }} && asdf uninstall {{ item.0.name }} {{ item.1 }}
  args:
    executable: bash
    removes: "{{ asdf_dir }}/installs/{{ item.0.name }}/{{ item.1 }}"
  with_subelements:
    - "{{ asdf_plugins }}"
    - delete_versions
    - flags:
      skip_missing: True
  when: asdf_plugins | length > 0
  become: True
  become_user: "{{ asdf_user }}"

- name: "set global app versions"
  shell:
    source {{ asdf_script }} && asdf global {{ item.name }} {{ item.global | default(item.versions | difference(item.delete_versions|default([])) | sort | first) }}
  args:
    executable: bash
  when: item.versions is defined
  with_items: "{{ asdf_plugins }}"
  become: True
  become_user: "{{ asdf_user }}"

- name: "set asdfrc"
  template:
    src: "asdfrc.j2"
    dest: "{{ asdf_config_file }}"
    owner: "{{ asdf_user }}"
    group: "{{ asdf_group }}"
    mode: 0644
  become: True
  become_user: "{{ asdf_user }}"

- name: "set group permissions"
  become: yes
  file:
    path: "{{ asdf_dir }}"
    owner: "{{ asdf_user }}"
    group: "{{ asdf_group }}"
    state: directory
    recurse: yes
